/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio11;

import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class Menu extends javax.swing.JFrame {
    HashTable hashTable;
    int tableSize;
    
    /**
     * Creates new form Menu
     */
    public Menu(int htSize) {
        initComponents();
        this.tableSize=htSize;
        hashTable = new HashTable(htSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Tabs = new javax.swing.JTabbedPane();
        BuscarxCodigo = new javax.swing.JPanel();
        txtCodBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botBuscar = new javax.swing.JButton();
        Agregar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botAgregar = new javax.swing.JButton();
        txtCodAgregar = new javax.swing.JTextField();
        txtNomAgregar = new javax.swing.JTextField();
        txtDirAgregar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tHashTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        txtCodBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Matrícula");

        botBuscar.setText("Buscar");
        botBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscarxCodigoLayout = new javax.swing.GroupLayout(BuscarxCodigo);
        BuscarxCodigo.setLayout(BuscarxCodigoLayout);
        BuscarxCodigoLayout.setHorizontalGroup(
            BuscarxCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarxCodigoLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(botBuscar)
                .addGap(69, 69, 69))
        );
        BuscarxCodigoLayout.setVerticalGroup(
            BuscarxCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscarxCodigoLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(BuscarxCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botBuscar))
                .addGap(50, 50, 50))
        );

        Tabs.addTab("Buscar", BuscarxCodigo);

        jLabel2.setText("Matrícula");

        jLabel3.setText("Nombre");

        jLabel4.setText("Dirección");

        botAgregar.setText("Agregar");
        botAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAgregarActionPerformed(evt);
            }
        });

        txtCodAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar);
        Agregar.setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDirAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botAgregar)
                .addGap(60, 60, 60))
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(botAgregar)
                    .addComponent(txtCodAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        Tabs.addTab("Agregar", Agregar);

        tHashTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Índice", "Código", "Nombre", "Dirección"
            }
        ));
        jScrollPane1.setViewportView(tHashTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodBuscarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCodBuscarActionPerformed

    private void txtCodAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodAgregarActionPerformed

    private void botBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBuscarActionPerformed
        // TODO add your handling code here:
        int matricula = Integer.parseInt( txtCodBuscar.getText() );
        hashTable.FindNode(matricula);
//        hashTable.FindNode( Integer.parseInt( txtCodBuscar.getText() ) );
    }//GEN-LAST:event_botBuscarActionPerformed

    private void botAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAgregarActionPerformed
        // TODO add your handling code here:
        int cod;
        String nombre;
        String direccion;
        cod = Integer.parseInt( txtCodAgregar.getText() );
        
        //Verificar que se llenen todos los campos
        if(txtCodAgregar.getText().isEmpty()||txtNomAgregar.getText().isEmpty()
                ||txtDirAgregar.getText().isEmpty()){
            return;
        }
        
        //Validar maricula
        if(cod<1000||cod>4999){
            JOptionPane.showMessageDialog(null, "Matrícula invalida: 999 < código < 5000");
            return;
        }
        
        nombre=txtNomAgregar.getText();
        direccion=txtDirAgregar.getText();
        
        Alumno alu = new Alumno(cod, nombre, direccion);
        
        hashTable.InsertNode(alu);
        hashTable.llenarTabla(tHashTable);
        
        
    }//GEN-LAST:event_botAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agregar;
    private javax.swing.JPanel BuscarxCodigo;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JButton botAgregar;
    private javax.swing.JButton botBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tHashTable;
    private javax.swing.JTextField txtCodAgregar;
    private javax.swing.JTextField txtCodBuscar;
    private javax.swing.JTextField txtDirAgregar;
    private javax.swing.JTextField txtNomAgregar;
    // End of variables declaration//GEN-END:variables
}
